[build]
  command = "ng build --configuration production"
  publish = "dist/maps-app"

[context.production]
  environment = { "NETLIFY_USE_YARN": "true" }

[[plugins]]
  package = "@netlify/angular-runtime"
